name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: Setup PHP Action
      # You may pin to the exact commit or the version.
      # uses: shivammathur/setup-php@cb8f453143149404c7fd670b5f37c91d395b3054
      uses: shivammathur/setup-php@2.25.1
      with:
        # Setup PHP version.
        php-version: # optional
        # Setup PHP version from a file.
        php-version-file: # optional
        # Setup PHP extensions.
        extensions: # optional
        # Set base ini file.
        ini-file: # optional, default is production
        # Add values to php.ini.
        ini-values: # optional
        # Setup code coverage driver.
        coverage: # optional
        # Setup popular tools globally.
        tools: # optional
